language: ruby
rvm:
  - 2.1
script: 'bundle exec rake build'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: 9.3
notifications:
  email:
    - hanka@lunarlogic.io
